name: lawndart
version: 0.10.0
author: Seth Ladd <sethladd@gmail.com>
description: An easier way to access storage APIs in the browser.
homepage: https://github.com/sethladd/lawndart
documentation: http://sethladd.github.com/lawndart/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.12.0
  build_test: ^2.0.0
  build_web_compilers: ^2.16.0
  test: ^1.16.0


