name: lawndart
version: 0.5.0
author: Seth Ladd <sethladd@gmail.com>
description: An easier way to access storage APIs in the browser.
homepage: https://github.com/sethladd/lawndart
documentation: http://sethladd.github.com/lawndart/
dependencies:
  meta: any
dev_dependencies:
  unittest: any
  hop: any
  browser: any
  web_ui: any
