name: lawndart
version: 0.10.0
description: An easier way to access storage APIs in the browser.
homepage: https://github.com/sethladd/lawndart
documentation: http://sethladd.github.com/lawndart/

environment:
  sdk: '>=3.4.0'

dependencies:
  web: ^1.0.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: any


